### PR TITLE
Change all apps button icon color to holo_blue_light

### LINKED ISSUE #5: bug: Update default all apps icon to accommodate light and dark navigation bar.
If we can't get the changed event of navigation bar background color, we can use a more bright color for default icon that can accommodate light and dark navigation bar.

### PR DESCRIPTION
**Pull request by utzcoz**
It will make all apps icon accommodate for light and dark navigation bar.

Close #5 

@electrikjesus , can you accept this new color?

### CODE REVIEW

**Review by electrikjesus — COMMENTED** [review]
I will have to test this as I think the white is actually replaced with the primary or secondary accent color by the theming service. On Bliss and other ROMs, the icons are light or dark, so maybe providing a different light icon might work better.

**Comment by utzcoz** [comment]
Actually, I don't find a method to receive the event that navigation bar changes the background color. From the previous debugging, the navigation bar doesn't expose the API to notify theme changing event. So I select a color that can work for light and dark theme for both occasion.

**Comment by utzcoz** [comment]
@electrikjesus I have extracted the color to a single color value.

**Comment by electrikjesus** [comment]
This works in my testing. Will be a good solution to build off of also. I say merge it ;)

**Pull request merged**
